plugins {
    alias(libs.plugins.spring.dependency.management)
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.ben.manes.versions)
}

allprojects {
    group = 'org.pkaq'
    version = '4.0.3.12'
}

subprojects {
    apply plugin: 'java-library'
	apply plugin: 'maven-publish'
    apply plugin: 'signing'

    apply plugin: 'io.spring.dependency-management'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        sourceCompatibility = '25'
        targetCompatibility = '25'
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
    }

    tasks.withType(Javadoc).configureEach {
        options.encoding = "UTF-8"
        options.addStringOption('Xdoclint:none', '-quiet')
    }

    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs.add("-parameters")

        options.compilerArgs += [
                "-Amapstruct.defaultComponentModel=spring",
                "-Amapstruct.suppressGeneratorTimestamp=true",
                "-Amapstruct.verbose=true"
        ]
    }

    test {
        useJUnitPlatform()
    }

    repositories {
        mavenLocal()
        maven {
            url "http://dev.jm-sk.com:12081/"
            allowInsecureProtocol = true
            credentials {
                username = 'admin'
                password = '7u8i9o0p'
            }
        }
//        maven { url 'https://central.sonatype.com/repository/maven-snapshots/' }
//        maven {
//            url "http://yy.pkaq.org:8082/artifactory/yunyue-public/"
//            allowInsecureProtocol = true
//            credentials {
//                username = 'yyfrog'
//                password = 'YYfrog7788'
//            }
//        }
        mavenCentral()
    }

    dependencies {
        implementation platform(libs.boot)
        implementation libs.lombok
        annotationProcessor libs.lombok

        implementation      libs.mapstruct
        annotationProcessor libs.mapstruct.processor

        testImplementation libs.test,
                           libs.webtest,
                           libs.security.test
        testRuntimeOnly libs.junit.platform.launcher

     }
}

