plugins {
    alias(libs.plugins.spring.dependency.management)
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.ben.manes.versions)
}

allprojects {
    group = 'io.nerv'
    version = '3.0.2'
}

subprojects {
    apply plugin: 'java-library'
	apply plugin: 'maven-publish'
    apply plugin: 'signing'

    apply plugin: 'io.spring.dependency-management'

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
    }

    tasks.withType(Javadoc).configureEach {
        options.encoding = "UTF-8"
        options.addStringOption('Xdoclint:none', '-quiet')
    }

    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs.add("-parameters")
    }

    repositories {
        mavenLocal()
        //maven {
        //    url "http://192.168.10.12:8082/artifactory/public/"
        //    allowInsecureProtocol = true
        //}
//        allowInsecureProtocol = true
        maven {
            url "http://192.168.10.16:8082/artifactory/yunyue-public/"
            allowInsecureProtocol = true
            credentials {
                username = 'yyfrog'
                password = 'YYfrog7788'
            }
        }
        mavenCentral()
    }

    dependencies {
        implementation platform(libs.boot)
        implementation libs.lombok
        annotationProcessor libs.lombok

        testImplementation libs.test,
                           libs.security.test

     }
}

