profile=aliyun
spring_dep=1.1.5
spring_boot_ver=3.2.5
ttl=2.14.5
mysql=8.0.33
mybatis_plus_starter=3.5.6
lombok=1.18.32
knife4j=4.3.0
hutool=5.8.27
jaxb_api=2.3.1
jasypt=3.0.5
p6spy=3.9.1
flyway=10.12.0
boot_admin=3.1.6
truelicense=1.33
caffeine=3.1.8
securityTest=6.2.4
jwt=9.38
jsr310=2.17.1
oracle=19.22.0.0
orai18n=12.1.0.2.0
springdoc=2.5.0
minio=8.5.10
org.gradle.jvmargs=-Dfile.encoding=UTF-8
systemProp.file.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configureondemand=true

