profile=dev

spring_dep=1.1.7
spring_boot_ver=3.4.5
lombok=1.18.38
security=5.3.4.RELEASE
rsa=1.1.5
alibaba=2023.0.3.2
cloud=2024.0.1
bootstrap=4.2.1
dubbo=3.3.4
dubbo_client=3.0.0
eva=3.0.0
job=3.1.0
hutool=5.8.38
knife4j=4.5.0
mysql=8.0.33
boot_admin=3.4.6
skywalking=9.4.0
springdoc=1.8.0
oauth2_config=2.6.8
oauth2_client=6.4.5

org.gradle.jvmargs=-Dfile.encoding=UTF-8
systemProp.file.encoding=UTF-8

org.gradle.parallel=true
org.gradle.configureondemand=true