profile=dev

spring_dep=1.1.7
spring_boot_ver=3.3.5
lombok=1.18.36
security=5.3.4.RELEASE
rsa=1.1.5
alibaba=2023.0.3.2
cloud=2023.0.3
bootstrap=4.1.4
dubbo=3.3.1
dubbo_client=2.4.3
eva=3.0.0
jwt=9.47
job=2.4.1
hutool=5.8.34
knife4j=4.5.0
mysql=8.0.33
boot_admin=3.4.1
skywalking=9.3.0
springdoc=1.8.0
oauth2_config=2.6.8
oauth2_client=6.3.4

org.gradle.jvmargs=-Dfile.encoding=UTF-8
systemProp.file.encoding=UTF-8

org.gradle.parallel=true
org.gradle.configureondemand=true