rootProject.name = 'yunyue'

include ':yunyue-web:yunyue-web-sys'
include ':yunyue-web:yunyue-web-auth'
include ':yunyue-web:yunyue-web-sa-auth'

include ':yunyue-core:yunyue-core-log'
include ':yunyue-core:yunyue-core-cache'
include ':yunyue-core:yunyue-core-common'
include ':yunyue-core:yunyue-core-data-mybatis'
include ':yunyue-core:yunyue-core-web'
include ':yunyue-core:yunyue-core-upload'
include ':yunyue-core:yunyue-core-websocket'


