if (project.file('../../publish.gradle').exists()) {
    apply from: '../../publish.gradle'
}
jar {
    archiveBaseName = 'eva-core-web'
}

project.description = 'eva web support with all base modules'

dependencies {

    api(libs.web) {
        exclude module: 'spring-boot-starter-tomcat'
    }
    api libs.undertow

    api project(":eva-core:eva-core-common"),
            libs.springdoc
}
