if (project.file('../../publish.gradle').exists()) {
    apply from: '../../publish.gradle'
}
jar {
    archiveBaseName = 'eva-web-sys'
}

project.description = 'sys jar with authority and system management'

dependencies {
    implementation project(":eva-core:eva-core-web"),
            project(":eva-core:eva-core-data-mybatis"),
            project(":eva-core:eva-core-log"),
            project(":eva-core:eva-core-cache"),
            libs.mysql

    implementation libs.mybatis.plus.starter,
            libs.mapstruct
    annotationProcessor libs.mapstruct.processor
    libs.lombok
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += [
            "-Amapstruct.defaultComponentModel=spring",
            "-Amapstruct.suppressGeneratorTimestamp=true",
            "-Amapstruct.verbose=true"
    ]
}