if (project.file('../../publish.gradle').exists()) {
    apply from: '../../publish.gradle'
}
project.archivesBaseName = 'yunyue-web-sa-auth'
project.description='we jar with system management'

dependencies {
    implementation     project(":yunyue-core:yunyue-core-web"),
            project(":yunyue-core:yunyue-core-log"),
            project(":yunyue-core:yunyue-core-data-mybatis"),
            project(":yunyue-core:yunyue-core-cache"),
            "${lib.mysql}",
            "${lib.sa_token_starter}",
            "${lib.sa_token_redis}",
            "${lib.sa_token_jwt}",
            "${lib.aj_captcha_starter}"
}
