if (project.file('../../publish.gradle').exists()) {
    apply from: '../../publish.gradle'
}

jar {
    archiveBaseName = 'eva-core-common'
}

project.description='eva common class'

dependencies {
    api libs.jaxb.api,
        libs.servlet.api
//        libs.jasypt

    api libs.aop,
        libs.jwt,
        libs.json,
        libs.springdoc,
        libs.validation
}
