if (project.file('../../publish.gradle').exists()) {
    apply from: '../../publish.gradle'
}

jar {
    archiveBaseName = 'eva-core-common'
}

project.description='eva common class'

dependencies {
    implementation 	libs.jaxb.api,
                    libs.jasypt

    api libs.hutool,
        libs.aop,
        libs.jwt,
        libs.json,
        libs.ttl,
        libs.validation
}
