project:
  version: 0.0.1
logging:
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 10GB
      clean-history-on-start: true
spring:
  profiles:
    default: dev
  config:
    import: classpath:config/eva/eva.yaml
  servlet:
    # 文件上传配置
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  # 国际化配置
  messages:
    basename: i18n/i18n, i18n/sys
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    # 时区
    default-property-inclusion: always
    serialization:
      #格式化输出
      indent_output: true
  main:
    allow-bean-definition-overriding: true
  web:
    locale: zh_CN
    locale-resolver: fixed
#  spring doc 配置
#springdoc:
#  swagger-ui:
#    disable-swagger-default-url: true
#  api-docs:
#    groups:
#      enabled: true
#    enabled: true
mybatis:
  type-handlers-package: org.pkaq.core.mybatis.enums
mybatis-plus:
  type-handlers-package: org.pkaq.core.mybatis.enums
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.pkaq.*.**.entity
  global-config:
    db-config:
      id-type: assign_id
      #      字段策略
      #      驼峰下划线转换
      table-underline: true
      logic-delete-value: 'UNIX_TIMESTAMP()' # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      where-strategy: not_empty
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 配置加密
jasypt:
  encryptor:
    password: ::eva
# server配置
server:
  servlet:
    context-path: /api
    # 编码
    encoding:
      charset: utf-8
      enabled: true
      force: true
  port: 9016
  #  2.3.0 新支持, 优雅关机
  shutdown: graceful
springdoc:
  default-flat-param-object: true
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
