debug: false
# 日志
logging:
  pattern:
    level: WARN
  # 日志文件配置
  file:
    path: /opt/data/logs/webapp.log
# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://182.61.49.92:12306/eva?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: eva
    password: eva666
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  hikari:
    minimum-idle: 3
    maximum-pool-size: 10
    max-lifetime: 3000
    connection-test-query: select 1
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main/java
  # redis 配置
  redis:
    host: 182.61.49.92
    port: 6379
    password: 8i9o0p
    timeout: 10000
    database: 0
  # 校验表结构
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
  # 生产环境禁用flyway
  flyway:
    enabled: false
jwt:
  # 图片上传
  upload:
    tempPath: E://evapic/temp
    storagePath: E://evapic/storage
    allowSuffixName: jpg,png,jpeg
  cookie:
    maxAge: 3600