if (project.file('../../publish.gradle').exists()) {
    apply from: '../../publish.gradle'
}
base.archivesName = 'eva-core-websocket'
project.description = "tool for websocket"

dependencies {
    implementation(libs.websocket){
        exclude module: 'spring-boot-starter-tomcat'
    }

    implementation libs.undertow

    implementation project(":eva-core:eva-core-common")

}
