debug: false
# 日志
logging:
  pattern:
    level: debug
# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://localhost:3306/jxc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ENC(dghf0DZZJA+vQ95xgHz5iA==)
    password: ENC(Yyk5bWPsCApaZ1yceumO4A==)
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  devtools:
    livereload:
      enabled: true