if (project.file('../../publish.gradle').exists()) {
    apply from: '../../publish.gradle'
}
jar {
    archiveBaseName = 'eva-core-license'
}
project.description = 'eva license support'

dependencies {

    implementation(libs.web) {
        exclude module: 'spring-boot-starter-tomcat'
    }

    implementation project(":eva-core:eva-core-common"),
            libs.undertow

    api libs.truelicense
}
