if (project.file('../../publish.gradle').exists()) {
    apply from: '../../publish.gradle'
}
jar {
    archiveBaseName = 'eva-core-license'
}
project.description = 'eva license support'

dependencies {

    implementation project(":eva-core:eva-core-common"),
                   libs.web

    api libs.truelicense
}
