if (project.file('../../publish.gradle').exists()) {
    apply from: '../../publish.gradle'
}
jar {
    archiveBaseName = 'eva-core-upload'
}
project.description = 'eva fileupload support '

dependencies {

    implementation(libs.web) {
        exclude module: 'spring-boot-starter-tomcat'
    }
    implementation libs.undertow,
            libs.minio

    implementation project(":eva-core:eva-core-common")
}
