#publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIiwHpFrDijV+GzwRTzWJk8D3j3jFfhsMFJ/7k1NTvBuLgL+TdIHgaMNOIEjHpXzuvX38J3FtOK8hLrySncVGOMCAwEAAQ==
spring:
  messages:
    basename: i18n/i18n
    encoding: UTF-8
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  mvc:
    date-format: yyyy-MM-dd
# 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/jxc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: jxc
    password: jxc
      # 公钥
    # 配置 connection-properties，启用加密，配置公钥。
#    druid:
#      filter:
#       config:
#         enabled: true
#      connection-properties: config.decrypt=true;config.decrypt.key={{publickey}}
server:
  servlet:
    context-path: /
  port: 80
  tomcat:
    uri-encoding: utf-8
debug: false
# 日志
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.pkaq.web.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  config:
    level: debug
