version: '3.0'
services:
  # MYSQL
  percona:
    image: percona/percona-server:latest
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1 --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      #设置root帐号密码
      MYSQL_ROOT_PASSWORD: 7u8i9o0p
    ports:
      - 12306:3306
    privileged: true
    volumes:
      #数据文件挂载
      - /etc/localtime:/etc/localtime:ro
      - /opt/data/percona/my.cnf.d:/etc/my.cnf.d
      #配置文件挂载
      - /opt/data/percona/data:/var/lib/mysql
      #日志文件挂载
      - /opt/data/percona/mysql-files:/var/lib/mysql-files
  # REDIS
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes --requirepass 7u8i9o0p
    privileged: true
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #数据文件挂载
      - /opt/data/redis/data:/data
      - /opt/data/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
  # NGINX    
  nginx:
    image: nginx:latest
    container_name: nginx
    privileged: true
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #配置文件挂载
      - /opt/data/nginx/nginx.conf:/etc/nginx/nginx.conf
      #静态资源根目录挂载
      - /opt/data/nginx/www:/usr/share/nginx/html
      #日志文件挂载
      - /opt/data/nginx/log:/var/log/nginx
    ports:
      - 80:80
  # 图片服务器
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data
    privileged: true
    restart: always
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: 7u8i9o0p
    volumes:
      - /opt/data/minio/config:/root/.minio
      - /opt/data/minio:/data
    ports:
      - 9000:9000
