spring:
  # flyway配置 对于非空数据库 需要开启此项避免报错
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration
    baseline-version: 0
    enabled: false
  servlet:
    # 文件上传配置
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  # 国际化配置
  messages:
    basename: i18n/i18n
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    # 时区
    time-zone: GMT+8
    default-property-inclusion: always
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      #格式化输出
      indent_output: true
    # 数据源
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      username: eva
      password: eva
      #    GsyjJCmmNRiHRVGmXdy+QErynoqC/cOBlt5V9dPZ+c2g2XwPc5+BbKrSxWLsyCGG
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://xilai.my.to:12306/eva?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&failOverReadOnly=false
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      max-lifetime: 3000
      connection-test-query: select 1
    devtools:
      livereload:
        enabled: true
      restart:
        additional-paths: src/main/java
    # redis 配置
    redis:
      host: xilai.my.to
      port: 6379
      password: 7u8i9o0p
      timeout: 10000
      database: 0
    flyway:
      enabled: false
    data:
      redis:
        repositories:
          enabled: false
# mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: io.nerv.*.**.entity
  global-config:
    #      刷新mapper 调试神器
    refresh: true
    db-config:
      id-type: assign_id
      #      字段策略
      #      驼峰下划线转换
      table-underline: true
      logic-delete-value: '0001' # 逻辑已删除值(默认为 1)
      logic-not-delete-value: '0000' # 逻辑未删除值(默认为 0)
      where-strategy: not_empty
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
# 配置加密
jasypt:
  encryptor:
    password: ::eva
# server配置
server:
  servlet:
    context-path: /api
    #  2.3.0 新支持, 优雅关机
    shutdown: graceful
    # 编码
    encoding:
      charset: utf-8
      enabled: true
      force: true
  port: 9016
eva:
  norepeat-check: false
  # 该配置必须在jwt配置前 30天有效
  cookie:
    maxAge: &maxAge 2592000
  # JWT配置
  jwt:
    # 是否持久化token
    persistence: false
    header: Authorization
    token-head: Bearer
    sign: PKAQ
    secert: 6MNSobBRCHGIO0fS6MNSobBRCHGIO0fS
    ttl: *maxAge
    # 6 小时
    alphaTtl: 21600000
    # 30 天
    bravoTtl: 2592000000
    # 过期阈值 默认6小时
    threshold: 21600000
  # 访问权限
  security:
    webstatic:
    # 无需鉴权路径(无条件访问)
    anonymous: /auth/login,/auth/logout,/wx/**,/doc/**,/actuator/**
    # 无需资源鉴权的路径
    permit: /auth/**,/wx/**,/doc/**,/actuator/**,/license/**
  # 资源权限
  resource-permission:
    # 是否启用
    enable: false
    strict: false
  # 数据权限
  datapermission:
    # 是否开启数据权限控制
    enable: true
    # 需要排除的表
    exclude-tables: sys_module_resources,sys_role_user
      # 缓存配置
      type: redis
      config:
        # 缓存名称 - 文件上传缓存
        - name: uploadfiles
          # 初始大小
          initialCapacity: 100
          # 过期时间(毫秒)
          secondsToExpire: 86400000
          # 重复提交缓存
        - name: repeatsubmit
          initialCapacity: 100
          secondsToExpire: 500
          # 字典缓存
        - name: dictdata
          initialCapacity: 100
          secondsToExpire: -1
          # 业务数据缓存
        - name: bizdata
          initialCapacity: 100
          secondsToExpire: 86400000
        - name: token
          initialCapacity: 1000
          secondsToExpire: 2592000
  # 错误日志
  errorlog:
    enabled: true
  # 业务日志
  bizlog:
    enabled: true
    impl: MybatisSupporter
#    监控配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
debug: true
# 日志
logging:
  # 日志文件配置 file 和 path只需配置一个 不可同时配置 ， 同时配置只生效file
  file:
    path: e:/applogs/webapp.log
  pattern:
    level: debug
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"