spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  messages:
    encoding: UTF-8
eva:
  license:
    ########## 私钥的配置信息 ###########
    priv:
      # 私钥的别名
      key_alias: private_license_key
      # privateKeyPwd（该密码是生成密钥对的密码 — 需要妥善保管，不能让使用者知道）
      key_pwd: 7u8i9o0p
      # keyStorePwd（该密码是访问密钥库的密码 — 使用 keytool 生成密钥对时设置，使用者知道该密码）
      keystore_pwd: 7u8i9o0p
      # 密钥库的地址（放在 resource 目录下）
      path: /license/private_license.store
    ########## 公钥的配置信息 ###########
    pub:
      # 公钥别名
      alias: publiccert
      # 该密码是访问密钥库的密码 — 使用 keytool 生成密钥对时设置，使用者知道该密码
      keystore_pwd: 7u8i9o0p
      # 公共库路径（放在 resource 目录下
      path: /license/publicCerts.store
      # 证书路径（我这边配置在了 linux 根路径下，即 /license.lic ）
      license: /license/license.lic
    # 项目的唯一识别码
    subject: eva
    ########## license content ###########
    # 发布日期
    issuedTime: 2020-02-09 00:00:00
    # 有效开始日期
    notBefore: 2020-02-09 00:00:00
    # 有效截止日期
    notAfter: 2029-02-09 23:16:00
    # ip 地址
    ipAddress: 192.168.0.107
    # mac 地址
    macAddress: 70-C9-4E-E6-6D-D1
    # 使用者类型，用户(user)、电脑(computer)、其他（else）
    consumerType: user
    # 证书允许使用的消费者数量
    consumerAmount: 1
    # 证书说明
    info: power by xiamen yungu
    #生成证书的地址
    licPath: D:\eva_license\license.lic
server:
  undertow:
    url-charset: UTF-8