spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #配置RSA的公钥访问地址
          jwk-set-uri: 'http://localhost:9871/auth/oauth/publicKey'
#      client:
#        registration:
#          client-id:
#          client-secret:
#        opaquetoken:
#          client-id:
#          client-secret:
#          introspection-uri: