spring:
  application:
    name: eva-cloud-gateway
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9599/rsa/publicKey'
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 192.168.10.59
        enabled: true
        service: eva-cloud-gateway
        group: DEV_GROUP
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      # 处理跨域问题
      globalcors:
        cors-configurations:
          # 匹配所有请求
          '[/**]':
            # 支持所有域
            allowedOrigins: "*"
            # 支持的跨域请求方法
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: eva-sys
  #          使用负载均衡, lb://服务名称
          uri: lb://eva-sys
  #          所有以 /api/sys 开头的请求都路由的上面的服务地址
          predicates:
              - Path=/api/sys/**
  #          将请求中的第一个路径去掉
          filters:
            - StripPrefix=1
        - id: eva-cloud-oauth-server
          uri: lb://eva-cloud-oauth-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
#           - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
#              args:
#                key-resolver: "#{@ipKeyResolver}"
#                每秒钟允许的并发请求数
#                redis-rate-limiter.replenishRate: 5
#                允许最大并发
#                redis-rate-limiter.burstCapacity: 15
#  Failed to start bean ‘documentationPluginsBootstrapper’; nested exception is java.lang.NullPointerException
#  Springboot2.6以后将SpringMVC 默认路径匹配策略从AntPathMatcher 更改为PathPatternParser，导致出错
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher