if (project.file('../../publish.gradle').exists()) {
    apply from: '../../publish.gradle'
}
project.archivesBaseName = 'yunyue-core-rabbitmq'
project.description = "tool for rabbimq"

dependencies {
    implementation project(":yunyue-core:yunyue-core-common"),
                   project(":yunyue-core:yunyue-core-log"),
                   "${lib.mongodb}",
                   "${lib.mybatisPlus}"
    api "${lib.rabbitmq}"
}
