if (project.file('../../publish.gradle').exists()) {
    apply from: '../../publish.gradle'
}

jar {
    archiveBaseName = 'eva-core-data-mybatis'
}

project.description = 'eva mybatis support'

dependencies {
    implementation project(":eva-core:eva-core-common"),
                   project(":eva-core:eva-core-log"),
                   libs.jdbc,
                   libs.p6spy,
                   libs.flyway

    api libs.mybatis.plus.starter,
        libs.mybatis.plus.jsqlparser
}
