if (project.file('../../publish.gradle').exists()) {
    apply from: '../../publish.gradle'
}
project.archivesBaseName = 'yunyue-core-license'
project.description='yunyue license support'

dependencies {

    implementation("${lib.web}"){
        exclude module: 'spring-boot-starter-tomcat'
    }

    implementation  project(":yunyue-core:yunyue-core-common"),
                    "${lib.undertow}"

    api             "${lib.truelicense}"
}
