-- 租户角色授权增量：平台模板、租户实例和套餐授权分离。
ALTER TABLE SYS_ROLE ADD COLUMN IF NOT EXISTS TEMPLATE_ROLE_ID BIGINT;
ALTER TABLE SYS_ROLE ADD COLUMN IF NOT EXISTS SYSTEM_ROLE VARCHAR(32);

-- 历史授权一律先关闭，再仅激活可证明合法的平台模板授权（fail-closed）。
ALTER TABLE SYS_TENANT_ROLE ADD COLUMN IF NOT EXISTS ACTIVE BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE SYS_TENANT_ROLE ADD COLUMN IF NOT EXISTS GRANTED_AT TIMESTAMP;
ALTER TABLE SYS_TENANT_ROLE ADD COLUMN IF NOT EXISTS REVOKED_AT TIMESTAMP;
ALTER TABLE SYS_TENANT_ROLE ADD COLUMN IF NOT EXISTS STATUS_REASON VARCHAR(200);

UPDATE SYS_TENANT_ROLE
SET ACTIVE = FALSE,
    REVOKED_AT = COALESCE(REVOKED_AT, CURRENT_TIMESTAMP),
    STATUS_REASON = 'MIGRATION_REJECTED_INVALID_TEMPLATE';

UPDATE SYS_TENANT_ROLE tenant_role
SET ACTIVE = TRUE,
    GRANTED_AT = COALESCE(tenant_role.GRANTED_AT, CURRENT_TIMESTAMP),
    REVOKED_AT = NULL,
    STATUS_REASON = 'MIGRATION_VALID_PLATFORM_TEMPLATE'
FROM SYS_ROLE role, SYS_TENANT tenant
WHERE role.ID = tenant_role.ROLE_ID
  AND tenant.ID = tenant_role.TENANT_ID
  AND COALESCE(tenant.DELETED, 0) = 0
  AND COALESCE(tenant.FROZEN, 0) <> 1
  AND COALESCE(role.TENANT_ID, 0) = 0
  AND COALESCE(role.DELETED, 0) = 0
  AND COALESCE(role.FROZEN, 0) <> 1;

CREATE TABLE IF NOT EXISTS SYS_TENANT_PACKAGE_GRANT (
    TENANT_ID BIGINT NOT NULL,
    PACKAGE_ID BIGINT NOT NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    GRANTED_AT TIMESTAMP,
    REVOKED_AT TIMESTAMP,
    CONSTRAINT PK_SYS_TENANT_PACKAGE_GRANT PRIMARY KEY (TENANT_ID, PACKAGE_ID)
);

CREATE INDEX IF NOT EXISTS IDX_SYS_TENANT_ROLE_ACTIVE
    ON SYS_TENANT_ROLE(TENANT_ID, ACTIVE);
CREATE INDEX IF NOT EXISTS IDX_SYS_TENANT_PACKAGE_GRANT_ACTIVE
    ON SYS_TENANT_PACKAGE_GRANT(TENANT_ID, ACTIVE);
CREATE INDEX IF NOT EXISTS IDX_SYS_ROLE_TEMPLATE
    ON SYS_ROLE(TEMPLATE_ROLE_ID);
CREATE UNIQUE INDEX IF NOT EXISTS UK_SYS_ROLE_TENANT_SYSTEM
    ON SYS_ROLE(TENANT_ID, SYSTEM_ROLE)
    WHERE SYSTEM_ROLE IS NOT NULL AND DELETED = 0;

-- 为所有既有有效租户幂等创建不可编辑的管理员角色实例。
INSERT INTO SYS_ROLE(
    ID, REVISION, DELETED, FROZEN, SORT, TENANT_ID, UTC_CREATE,
    CODE, NAME, DATA_SCOPE, SYSTEM_ROLE)
SELECT (hashtextextended(tenant.ID::text || ':TENANT_ADMIN', 0) & 9223372036854775807),
       0, 0, 9999, 0, tenant.ID, CURRENT_TIMESTAMP,
       'ROLE_TENANT_ADMIN_' || tenant.ID::text, '租户管理员', '0000', 'TENANT_ADMIN'
FROM SYS_TENANT tenant
WHERE COALESCE(tenant.DELETED, 0) = 0
  AND COALESCE(tenant.FROZEN, 0) <> 1
  AND tenant.ADMIN_ID IS NOT NULL
ON CONFLICT DO NOTHING;

INSERT INTO SYS_ROLEUSER_REF(ROLE_ID, USER_ID)
SELECT role.ID, tenant.ADMIN_ID
FROM SYS_ROLE role
JOIN SYS_TENANT tenant ON tenant.ID = role.TENANT_ID
WHERE role.SYSTEM_ROLE = 'TENANT_ADMIN'
  AND COALESCE(role.DELETED, 0) = 0
  AND COALESCE(tenant.DELETED, 0) = 0
  AND COALESCE(tenant.FROZEN, 0) <> 1
  AND tenant.ADMIN_ID IS NOT NULL
ON CONFLICT (ROLE_ID, USER_ID) DO NOTHING;

-- 将合法历史模板授权资源并入现有物化能力；既有人工裁剪结果不被删除。
INSERT INTO SYS_TENANT_RESOURCE(TENANT_ID, RESOURCE_ID)
SELECT tenant_role.TENANT_ID, role_resource.RESOURCE_ID
FROM SYS_TENANT_ROLE tenant_role
JOIN SYS_ROLERES_REF role_resource ON role_resource.ROLE_ID = tenant_role.ROLE_ID
WHERE tenant_role.ACTIVE = TRUE
ON CONFLICT (TENANT_ID, RESOURCE_ID) DO NOTHING;

-- 管理员获得租户全部现有有效能力；重复执行不会重复授权。
INSERT INTO SYS_ROLERES_REF(ROLE_ID, RESOURCE_ID)
SELECT role.ID, tenant_resource.RESOURCE_ID
FROM SYS_ROLE role
JOIN SYS_TENANT_RESOURCE tenant_resource ON tenant_resource.TENANT_ID = role.TENANT_ID
WHERE role.SYSTEM_ROLE = 'TENANT_ADMIN'
  AND COALESCE(role.DELETED, 0) = 0
ON CONFLICT (ROLE_ID, RESOURCE_ID) DO NOTHING;
