-- schema tenant 模式控制面元数据；standalone 模式不会读取或使用该列。
ALTER TABLE SYS_TENANT ADD COLUMN IF NOT EXISTS SCHEMA_NAME VARCHAR(63);
--#

CREATE UNIQUE INDEX IF NOT EXISTS UK_SYS_TENANT_SCHEMA_NAME
    ON SYS_TENANT(SCHEMA_NAME)
    WHERE SCHEMA_NAME IS NOT NULL AND DELETED = 0;
--#

ALTER TABLE SYS_TENANT DROP CONSTRAINT IF EXISTS CK_SYS_TENANT_SCHEMA_NAME;
--#
ALTER TABLE SYS_TENANT ADD CONSTRAINT CK_SYS_TENANT_SCHEMA_NAME
    CHECK (SCHEMA_NAME IS NULL OR SCHEMA_NAME ~ '^[a-z][a-z0-9_]{0,62}$');
--#

-- schema 标识符仅在数据库内部通过 format(%I) 安全引用，应用层始终使用绑定参数。
CREATE OR REPLACE FUNCTION EVA_PROVISION_TENANT_SCHEMA(P_SCHEMA_NAME TEXT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    IF P_SCHEMA_NAME IS NULL OR P_SCHEMA_NAME !~ '^[a-z][a-z0-9_]{0,62}$' THEN
        RAISE EXCEPTION 'invalid tenant schema name';
    END IF;
    EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', P_SCHEMA_NAME);
END;
$$;
--#
