-- 业务日志统一存放在平台控制面 schema；租户 schema 不创建日志表。
ALTER TABLE LOG_BIZ ADD COLUMN IF NOT EXISTS USER_ID BIGINT;
ALTER TABLE LOG_BIZ ADD COLUMN IF NOT EXISTS SUCCESS BOOLEAN NOT NULL DEFAULT TRUE;
UPDATE LOG_BIZ SET TENANT_ID = 0 WHERE TENANT_ID IS NULL;
ALTER TABLE LOG_BIZ ALTER COLUMN TENANT_ID SET DEFAULT 0;
ALTER TABLE LOG_BIZ ALTER COLUMN TENANT_ID SET NOT NULL;
--#

UPDATE LOG_ERROR SET TENANT_ID = 0 WHERE TENANT_ID IS NULL;
ALTER TABLE LOG_ERROR ALTER COLUMN TENANT_ID SET DEFAULT 0;
ALTER TABLE LOG_ERROR ALTER COLUMN TENANT_ID SET NOT NULL;
UPDATE SYS_LOGIN_LOG SET TENANT_ID = 0 WHERE TENANT_ID IS NULL;
ALTER TABLE SYS_LOGIN_LOG ALTER COLUMN TENANT_ID SET DEFAULT 0;
ALTER TABLE SYS_LOGIN_LOG ALTER COLUMN TENANT_ID SET NOT NULL;
--#

CREATE TABLE IF NOT EXISTS LOG_BIZ_ARCHIVE (
    ID BIGINT PRIMARY KEY,
    TENANT_ID BIGINT NOT NULL DEFAULT 0,
    USER_ID BIGINT,
    OPERATOR VARCHAR(100),
    OPERATE_TYPE VARCHAR(32),
    OPERATE_DATETIME VARCHAR(32) NOT NULL,
    SPEND_TIME VARCHAR(32),
    DESCRIPTION VARCHAR(1000),
    M_CODE VARCHAR(100),
    B_ID VARCHAR(100),
    CLASS_NAME VARCHAR(300),
    METHOD VARCHAR(200),
    PARAMS TEXT,
    RESPONSE TEXT,
    DEVICE VARCHAR(64),
    VERSION VARCHAR(64),
    SUCCESS BOOLEAN NOT NULL DEFAULT TRUE,
    ARCHIVED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--#

CREATE INDEX IF NOT EXISTS IDX_LOG_BIZ_TENANT_TIME_ID
    ON LOG_BIZ(TENANT_ID, OPERATE_DATETIME DESC, ID DESC);
CREATE INDEX IF NOT EXISTS IDX_LOG_BIZ_TENANT_MODULE_TYPE_TIME
    ON LOG_BIZ(TENANT_ID, M_CODE, OPERATE_TYPE, OPERATE_DATETIME DESC);
CREATE INDEX IF NOT EXISTS IDX_LOG_BIZ_TENANT_USER_TIME
    ON LOG_BIZ(TENANT_ID, USER_ID, OPERATE_DATETIME DESC);
CREATE INDEX IF NOT EXISTS IDX_LOG_BIZ_TENANT_BIZ_TIME
    ON LOG_BIZ(TENANT_ID, B_ID, OPERATE_DATETIME DESC);
--#

CREATE INDEX IF NOT EXISTS IDX_LOG_BIZ_ARCHIVE_TENANT_TIME_ID
    ON LOG_BIZ_ARCHIVE(TENANT_ID, OPERATE_DATETIME DESC, ID DESC);
CREATE INDEX IF NOT EXISTS IDX_LOG_BIZ_ARCHIVE_TENANT_MODULE_TYPE_TIME
    ON LOG_BIZ_ARCHIVE(TENANT_ID, M_CODE, OPERATE_TYPE, OPERATE_DATETIME DESC);
CREATE INDEX IF NOT EXISTS IDX_LOG_BIZ_ARCHIVE_TENANT_USER_TIME
    ON LOG_BIZ_ARCHIVE(TENANT_ID, USER_ID, OPERATE_DATETIME DESC);
CREATE INDEX IF NOT EXISTS IDX_LOG_BIZ_ARCHIVE_TENANT_BIZ_TIME
    ON LOG_BIZ_ARCHIVE(TENANT_ID, B_ID, OPERATE_DATETIME DESC);
