-- 新增角色资源关系表（扁平化存储，用于RBAC权限校验）
CREATE TABLE IF NOT EXISTS SYS_ROLE_RESOURCE (
    ID              BIGINT          NOT NULL    PRIMARY KEY,
    ROLE_ID         BIGINT          NOT NULL    COMMENT '角色ID',
    RESOURCE_PATH   VARCHAR(255)    NOT NULL    COMMENT '资源路径',
    HTTP_METHOD     VARCHAR(10)     NOT NULL    COMMENT 'HTTP方法(GET/POST/PUT/DELETE/*)'
);

CREATE INDEX IDX_ROLE_RESOURCE_ROLE_ID ON SYS_ROLE_RESOURCE(ROLE_ID);

-- 为SYS_USER添加权限版本号字段（若不存在）
ALTER TABLE SYS_USER ADD COLUMN IF NOT EXISTS PERM_VER BIGINT DEFAULT 0 COMMENT '权限版本号';
