CREATE TABLE IF NOT EXISTS SYS_NOTICE (
    ID BIGINT PRIMARY KEY,
    REVISION INTEGER,
    DELETED BIGINT NOT NULL DEFAULT 0,
    FROZEN INTEGER DEFAULT 0,
    SORT DOUBLE PRECISION NOT NULL DEFAULT 0,
    CREATE_ID BIGINT,
    CREATE_BY VARCHAR(100),
    UTC_CREATE TIMESTAMP,
    MODIFY_ID BIGINT,
    MODIFY_BY VARCHAR(100),
    UTC_MODIFY TIMESTAMP,
    REMARK VARCHAR(400),
    TITLE VARCHAR(200) NOT NULL,
    CONTENT TEXT,
    TYPE VARCHAR(40) NOT NULL,
    AVATAR VARCHAR(500),
    DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_SYS_NOTICE_TYPE ON SYS_NOTICE(TYPE);
CREATE INDEX IF NOT EXISTS IDX_SYS_NOTICE_DATETIME ON SYS_NOTICE(DATETIME DESC);
