ALTER TABLE LOG_ERROR ADD COLUMN IF NOT EXISTS FINGERPRINT VARCHAR(64);
ALTER TABLE LOG_ERROR ADD COLUMN IF NOT EXISTS EXCEPTION_TYPE VARCHAR(300);
ALTER TABLE LOG_ERROR ADD COLUMN IF NOT EXISTS SUMMARY VARCHAR(1000);
ALTER TABLE LOG_ERROR ADD COLUMN IF NOT EXISTS TRACE_ID VARCHAR(128);
ALTER TABLE LOG_ERROR ADD COLUMN IF NOT EXISTS FIRST_OCCURRED_AT TIMESTAMP;
ALTER TABLE LOG_ERROR ADD COLUMN IF NOT EXISTS LAST_OCCURRED_AT TIMESTAMP;
ALTER TABLE LOG_ERROR ADD COLUMN IF NOT EXISTS OCCURRENCE_COUNT BIGINT NOT NULL DEFAULT 1;
ALTER TABLE LOG_ERROR ADD COLUMN IF NOT EXISTS STATUS VARCHAR(16) NOT NULL DEFAULT 'OPEN';
--#
UPDATE LOG_ERROR
SET FINGERPRINT = MD5(COALESCE(ID::TEXT, '')) || MD5(COALESCE(ID::TEXT, '') || ':legacy'),
    FIRST_OCCURRED_AT = COALESCE(FIRST_OCCURRED_AT, CURRENT_TIMESTAMP),
    LAST_OCCURRED_AT = COALESCE(LAST_OCCURRED_AT, CURRENT_TIMESTAMP),
    SUMMARY = COALESCE(SUMMARY, LEFT(EX_DESC, 1000)),
    EXCEPTION_TYPE = COALESCE(EXCEPTION_TYPE, 'legacy')
WHERE FINGERPRINT IS NULL;
--#
ALTER TABLE LOG_ERROR DROP COLUMN IF EXISTS EX_DESC;
--#
ALTER TABLE LOG_ERROR ALTER COLUMN FINGERPRINT SET NOT NULL;
--#
CREATE UNIQUE INDEX IF NOT EXISTS UK_LOG_ERROR_TENANT_FINGERPRINT
    ON LOG_ERROR(TENANT_ID, FINGERPRINT);
CREATE INDEX IF NOT EXISTS IDX_LOG_ERROR_TENANT_LAST_OCCURRED
    ON LOG_ERROR(TENANT_ID, LAST_OCCURRED_AT DESC);
