ALTER TABLE SYS_LOGIN_LOG ADD COLUMN IF NOT EXISTS SESSION_ID VARCHAR(64);
ALTER TABLE SYS_LOGIN_LOG ADD COLUMN IF NOT EXISTS DEVICE_TYPE VARCHAR(64);
ALTER TABLE SYS_LOGIN_LOG ADD COLUMN IF NOT EXISTS DEVICE_MODEL VARCHAR(128);
ALTER TABLE SYS_LOGIN_LOG ADD COLUMN IF NOT EXISTS OS_NAME VARCHAR(64);
ALTER TABLE SYS_LOGIN_LOG ADD COLUMN IF NOT EXISTS OS_VERSION VARCHAR(64);
ALTER TABLE SYS_LOGIN_LOG ADD COLUMN IF NOT EXISTS BROWSER_NAME VARCHAR(64);
ALTER TABLE SYS_LOGIN_LOG ADD COLUMN IF NOT EXISTS BROWSER_VERSION VARCHAR(64);
ALTER TABLE SYS_LOGIN_LOG ADD COLUMN IF NOT EXISTS DEVICE_FINGERPRINT VARCHAR(64);
ALTER TABLE SYS_LOGIN_LOG ADD COLUMN IF NOT EXISTS RISK_FLAGS VARCHAR(200);
ALTER TABLE SYS_LOGIN_LOG ADD COLUMN IF NOT EXISTS LAST_ACTIVE_AT TIMESTAMP;
ALTER TABLE SYS_LOGIN_LOG ADD COLUMN IF NOT EXISTS LOGOUT_AT TIMESTAMP;
ALTER TABLE SYS_LOGIN_LOG ADD COLUMN IF NOT EXISTS LOGOUT_REASON VARCHAR(64);
--#
CREATE INDEX IF NOT EXISTS IDX_SYS_LOGIN_LOG_SESSION_ID ON SYS_LOGIN_LOG(SESSION_ID);
CREATE INDEX IF NOT EXISTS IDX_SYS_LOGIN_LOG_USER_DEVICE
    ON SYS_LOGIN_LOG(TENANT_ID, USER_ID, DEVICE_FINGERPRINT, UTC_CREATE DESC);
