if (project.file('../../publish.gradle').exists()) {
    apply from: '../../publish.gradle'
}
jar {
    archiveBaseName = 'eva-web-auth'
}
project.description = 'web auth module'

dependencies {
    api     project(":eva-web:eva-web-core"),
            project(":eva-core:eva-core-cache"),
            project(":eva-core:eva-core-log"),
            project(":eva-core:eva-core-data-mybatis"),
            libs.security
}
