spring:
  profiles:
    active: prod
  # flyway配置 对于非空数据库 需要开启此项避免报错
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration
# mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.pkaq.*.**.entity
  global-config:
#      刷新mapper 调试神器
    refresh: true
    db-config:
      id-type: uuid
#      字段策略
      field-strategy: not_empty
#      驼峰下划线转换
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
# JWT配置
jwt:
  header: Authorization
  token-head: Bearer
  sign: PKAQ
  secert: aHR0cDovL3BrYXEub3Jn
  ttl: 15000
# 配置加密
jasypt:
  encryptor:
    password: eva
# server配置
server:
  servlet:
    context-path: /api
  port: 9009
  tomcat:
    uri-encoding: utf-8
# 业务日志
bizlog:
  enabled: false
  impl: org.pkaq.core.bizlog.supporter.mybatis.MybatisSupporter
  basePackage:  org.pkaq.web