spring:
  profiles:
    active: dev
  # flyway配置 对于非空数据库 需要开启此项避免报错
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.pkaq.*.**.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
# for sys
jwt:
  header: Authorization
  token-head: Bearer
  sign: PKAQ
  secert: aHR0cDovL3BrYXEub3Jn
  ttl: 3600000
jasypt:
  encryptor:
    password: eva
server:
  servlet:
    context-path: /
  port: 80
  tomcat:
    uri-encoding: utf-8