server:
  servlet:
    context-path: /
  port: 80
  tomcat:
    uri-encoding: utf-8
debug: false
logging:
  pattern:
    level: debug
# 数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/jxc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ENC(dghf0DZZJA+vQ95xgHz5iA==)
    password: ENC(TNbKfi0lHjpfPcdepEnR5oKHikoDfVr+/amPonxytqK5u+B8Pid7k4hmlGUOhv+6QxEuB3gjJPPn7L8ishuFYym/Gr59qRO6Uf5/XiyT+3FUTujtyybxUjTyo4CO1wKe+zubp27QVYM=)
      # 公钥
    # 配置 connection-properties，启用加密，配置公钥。
    druid:
      filter:
       config:
         enabled: true
      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKR1ENwsJ6hxA79M9d6nOjCl4MNXHPtb9cwOWLnmjYDFOx57yogXDBWp0QnGKs1qZbfyaM3X6hsyO/m/7yTj5zUCAwEAAQ==
      driver-class-name: com.mysql.jdbc.Driver
  devtools:
    livereload:
      enabled: true
# 日志
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.pkaq.*.**.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
# for sys
jwt:
  header: Authorization
  token-head: Bearer
  sign: PKAQ
  secert: aHR0cDovL3BrYXEub3Jn
  ttl: 3600000
jasypt:
  encryptor:
    password: eva