debug: false
# 日志
logging:
  pattern:
    level: debug
# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://192.168.10.166:3306/eva?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ENC(+zmfSWY7K4obhKN5smFdzQ==)
    password: ENC(U10aDi9wVi6VlEp8pMHgpQ==)
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  devtools:
    livereload:
      enabled: true