if (project.file('../../publish.gradle').exists()) {
    apply from: '../../publish.gradle'
}
project.archivesBaseName = 'yunyue-core-upload'
project.description='yunyue fileupload support '

dependencies {

    implementation("${lib.web}"){
        exclude module: 'spring-boot-starter-tomcat'
    }
    implementation "${lib.undertow}",
                    "${lib.minio}",
                    "${lib.aliyun_sdk_oss}"

    implementation project(":yunyue-core:yunyue-core-common")
}
