if (project.file('../../publish.gradle').exists()) {
    apply from: '../../publish.gradle'
}
project.archivesBaseName = 'yunyue-web-auth'
project.description='we jar with system management'

dependencies {
    api     project(":yunyue-core:yunyue-core-web"),
            project(":yunyue-core:yunyue-core-log"),
            project(":yunyue-core:yunyue-core-data-mybatis"),
            project(":yunyue-core:yunyue-core-cache"),
            project(":yunyue-web:yunyue-web-sys"),
            "${lib.mysql}",
            "${lib.security}"
}
