-- 在租户 schema 的事务级 search_path 下执行。
CREATE TABLE IF NOT EXISTS EVA_TENANT_SCHEMA_VERSION (
    VERSION VARCHAR(50) PRIMARY KEY,
    INSTALLED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO EVA_TENANT_SCHEMA_VERSION(VERSION)
VALUES ('1')
ON CONFLICT (VERSION) DO NOTHING;

CREATE TABLE IF NOT EXISTS SYS_USER (
    ID BIGINT PRIMARY KEY,
    REVISION INTEGER,
    DELETED BIGINT NOT NULL DEFAULT 0,
    FROZEN INTEGER DEFAULT 0,
    SORT DOUBLE PRECISION NOT NULL DEFAULT 0,
    CREATE_ID BIGINT,
    CREATE_BY VARCHAR(100),
    UTC_CREATE TIMESTAMP,
    MODIFY_ID BIGINT,
    MODIFY_BY VARCHAR(100),
    UTC_MODIFY TIMESTAMP,
    REMARK VARCHAR(400),
    CODE VARCHAR(100),
    ACCOUNT VARCHAR(100),
    PASSWORD VARCHAR(200),
    AVATAR VARCHAR(500),
    NAME VARCHAR(100),
    NICK_NAME VARCHAR(100),
    TEL VARCHAR(40),
    EMAIL VARCHAR(100),
    LAST_IP VARCHAR(64),
    LAST_LOGIN DATE,
    DEPT_ID BIGINT,
    PERM_VER BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS UK_SYS_USER_ACCOUNT
    ON SYS_USER(ACCOUNT) WHERE DELETED = 0;
CREATE INDEX IF NOT EXISTS IDX_SYS_USER_DEPT_ID ON SYS_USER(DEPT_ID);
