-- 在租户 schema 的事务级 search_path 下执行。
CREATE TABLE IF NOT EXISTS EVA_TENANT_SCHEMA_VERSION (
    VERSION VARCHAR(50) PRIMARY KEY,
    INSTALLED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO EVA_TENANT_SCHEMA_VERSION(VERSION)
VALUES ('1')
ON CONFLICT (VERSION) DO NOTHING;

CREATE TABLE IF NOT EXISTS SYS_USER (
    ID BIGINT PRIMARY KEY,
    REVISION INTEGER,
    DELETED BIGINT NOT NULL DEFAULT 0,
    FROZEN INTEGER DEFAULT 0,
    SORT DOUBLE PRECISION NOT NULL DEFAULT 0,
    CREATE_ID BIGINT,
    CREATE_BY VARCHAR(100),
    UTC_CREATE TIMESTAMP,
    MODIFY_ID BIGINT,
    MODIFY_BY VARCHAR(100),
    UTC_MODIFY TIMESTAMP,
    REMARK VARCHAR(400),
    CODE VARCHAR(100),
    ACCOUNT VARCHAR(100),
    PASSWORD VARCHAR(200),
    AVATAR VARCHAR(500),
    NAME VARCHAR(100),
    NICK_NAME VARCHAR(100),
    TEL VARCHAR(40),
    EMAIL VARCHAR(100),
    LAST_IP VARCHAR(64),
    LAST_LOGIN DATE,
    DEPT_ID BIGINT,
    PERM_VER BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS UK_SYS_USER_ACCOUNT
    ON SYS_USER(ACCOUNT) WHERE DELETED = 0;
CREATE INDEX IF NOT EXISTS IDX_SYS_USER_DEPT_ID ON SYS_USER(DEPT_ID);
CREATE INDEX IF NOT EXISTS IDX_SYS_USER_TEL ON SYS_USER(TEL);
CREATE INDEX IF NOT EXISTS IDX_SYS_USER_EMAIL ON SYS_USER(EMAIL);

CREATE TABLE IF NOT EXISTS SYS_ORGANIZATION (
    ID BIGINT PRIMARY KEY,
    REVISION INTEGER,
    DELETED BIGINT NOT NULL DEFAULT 0,
    FROZEN INTEGER DEFAULT 0,
    SORT DOUBLE PRECISION NOT NULL DEFAULT 0,
    CREATE_ID BIGINT,
    CREATE_BY VARCHAR(100),
    UTC_CREATE TIMESTAMP,
    MODIFY_ID BIGINT,
    MODIFY_BY VARCHAR(100),
    UTC_MODIFY TIMESTAMP,
    REMARK VARCHAR(400),
    NAME VARCHAR(100),
    CODE VARCHAR(100),
    PID BIGINT NOT NULL DEFAULT 0,
    PATH VARCHAR(1000),
    ISLEAF BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS UK_SYS_ORGANIZATION_SIBLING_CODE
    ON SYS_ORGANIZATION(PID, CODE) WHERE DELETED = 0;
CREATE INDEX IF NOT EXISTS IDX_SYS_ORGANIZATION_PID ON SYS_ORGANIZATION(PID);
CREATE INDEX IF NOT EXISTS IDX_SYS_ORGANIZATION_PATH ON SYS_ORGANIZATION(PATH);
CREATE INDEX IF NOT EXISTS IDX_SYS_ORGANIZATION_SORT ON SYS_ORGANIZATION(PID, SORT);

CREATE TABLE IF NOT EXISTS SYS_POST (
    ID BIGINT PRIMARY KEY,
    REVISION INTEGER,
    DELETED BIGINT NOT NULL DEFAULT 0,
    FROZEN INTEGER DEFAULT 0,
    SORT DOUBLE PRECISION NOT NULL DEFAULT 0,
    CREATE_ID BIGINT,
    CREATE_BY VARCHAR(100),
    UTC_CREATE TIMESTAMP,
    MODIFY_ID BIGINT,
    MODIFY_BY VARCHAR(100),
    UTC_MODIFY TIMESTAMP,
    REMARK VARCHAR(400),
    CODE VARCHAR(100),
    TITLE VARCHAR(100),
    LEVEL VARCHAR(4),
    PID BIGINT NOT NULL DEFAULT 0,
    PATH VARCHAR(1000),
    ISLEAF BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS UK_SYS_POST_SIBLING_CODE
    ON SYS_POST(PID, CODE) WHERE DELETED = 0;
CREATE INDEX IF NOT EXISTS IDX_SYS_POST_PID ON SYS_POST(PID);
CREATE INDEX IF NOT EXISTS IDX_SYS_POST_PATH ON SYS_POST(PATH);
CREATE INDEX IF NOT EXISTS IDX_SYS_POST_SORT ON SYS_POST(PID, SORT);

CREATE TABLE IF NOT EXISTS SYS_DICT (
    ID BIGINT PRIMARY KEY,
    REVISION INTEGER,
    DELETED BIGINT NOT NULL DEFAULT 0,
    FROZEN INTEGER DEFAULT 0,
    SORT DOUBLE PRECISION NOT NULL DEFAULT 0,
    CREATE_ID BIGINT,
    CREATE_BY VARCHAR(100),
    UTC_CREATE TIMESTAMP,
    MODIFY_ID BIGINT,
    MODIFY_BY VARCHAR(100),
    UTC_MODIFY TIMESTAMP,
    REMARK VARCHAR(400),
    TYPE VARCHAR(100),
    CODE VARCHAR(100),
    NAME VARCHAR(200)
);

CREATE INDEX IF NOT EXISTS IDX_SYS_DICT_TYPE ON SYS_DICT(TYPE);
CREATE UNIQUE INDEX IF NOT EXISTS UK_SYS_DICT_CODE ON SYS_DICT(CODE) WHERE DELETED = 0;

CREATE TABLE IF NOT EXISTS SYS_DICT_ITEM (
    ID BIGINT PRIMARY KEY,
    REVISION INTEGER,
    DELETED BIGINT NOT NULL DEFAULT 0,
    FROZEN INTEGER DEFAULT 0,
    SORT DOUBLE PRECISION NOT NULL DEFAULT 0,
    CREATE_ID BIGINT,
    CREATE_BY VARCHAR(100),
    UTC_CREATE TIMESTAMP,
    MODIFY_ID BIGINT,
    MODIFY_BY VARCHAR(100),
    UTC_MODIFY TIMESTAMP,
    REMARK VARCHAR(400),
    MAIN_ID BIGINT NOT NULL,
    D_CODE VARCHAR(100) NOT NULL,
    D_VALUE VARCHAR(200) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS UK_SYS_DICT_ITEM_MAIN_CODE
    ON SYS_DICT_ITEM(MAIN_ID, D_CODE) WHERE DELETED = 0;
CREATE INDEX IF NOT EXISTS IDX_SYS_DICT_ITEM_MAIN_ID ON SYS_DICT_ITEM(MAIN_ID);
CREATE INDEX IF NOT EXISTS IDX_SYS_DICT_ITEM_MAIN_SORT ON SYS_DICT_ITEM(MAIN_ID, SORT);

CREATE TABLE IF NOT EXISTS SYS_ROLE (
    ID BIGINT PRIMARY KEY,
    REVISION INTEGER,
    DELETED BIGINT NOT NULL DEFAULT 0,
    FROZEN INTEGER DEFAULT 0,
    SORT DOUBLE PRECISION NOT NULL DEFAULT 0,
    CREATE_ID BIGINT,
    CREATE_BY VARCHAR(100),
    UTC_CREATE TIMESTAMP,
    MODIFY_ID BIGINT,
    MODIFY_BY VARCHAR(100),
    UTC_MODIFY TIMESTAMP,
    REMARK VARCHAR(400),
    CODE VARCHAR(100),
    NAME VARCHAR(100),
    DATA_SCOPE VARCHAR(50) DEFAULT '0000',
    DATA_ORG_IDS TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS UK_SYS_ROLE_CODE ON SYS_ROLE(CODE) WHERE DELETED = 0;

CREATE TABLE IF NOT EXISTS SYS_ROLEUSER_REF (
    ROLE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CONSTRAINT PK_SYS_ROLEUSER_REF PRIMARY KEY (ROLE_ID, USER_ID)
);

CREATE INDEX IF NOT EXISTS IDX_SYS_ROLEUSER_ROLE_ID ON SYS_ROLEUSER_REF(ROLE_ID);
CREATE INDEX IF NOT EXISTS IDX_SYS_ROLEUSER_USER_ID ON SYS_ROLEUSER_REF(USER_ID);

CREATE TABLE IF NOT EXISTS SYS_ROLERES_REF (
    ROLE_ID BIGINT NOT NULL,
    RESOURCE_ID BIGINT NOT NULL,
    CONSTRAINT PK_SYS_ROLERES_REF PRIMARY KEY (ROLE_ID, RESOURCE_ID)
);

CREATE INDEX IF NOT EXISTS IDX_SYS_ROLERES_ROLE_ID ON SYS_ROLERES_REF(ROLE_ID);
CREATE INDEX IF NOT EXISTS IDX_SYS_ROLERES_RESOURCE_ID ON SYS_ROLERES_REF(RESOURCE_ID);

CREATE TABLE IF NOT EXISTS SYS_POSTUSER_REF (
    ID BIGINT PRIMARY KEY,
    POST_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CREATE_ID BIGINT,
    CREATE_BY VARCHAR(100),
    UTC_CREATE TIMESTAMP,
    CONSTRAINT UK_SYS_POSTUSER_POST_USER UNIQUE (POST_ID, USER_ID)
);

CREATE INDEX IF NOT EXISTS IDX_SYS_POSTUSER_USER_ID ON SYS_POSTUSER_REF(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_SYS_POSTUSER_POST_ID ON SYS_POSTUSER_REF(POST_ID);

CREATE TABLE IF NOT EXISTS SYS_NOTICE (
    ID BIGINT PRIMARY KEY,
    REVISION INTEGER,
    DELETED BIGINT NOT NULL DEFAULT 0,
    FROZEN INTEGER DEFAULT 0,
    SORT DOUBLE PRECISION NOT NULL DEFAULT 0,
    CREATE_ID BIGINT,
    CREATE_BY VARCHAR(100),
    UTC_CREATE TIMESTAMP,
    MODIFY_ID BIGINT,
    MODIFY_BY VARCHAR(100),
    UTC_MODIFY TIMESTAMP,
    REMARK VARCHAR(400),
    TITLE VARCHAR(200) NOT NULL,
    CONTENT TEXT,
    TYPE VARCHAR(40) NOT NULL,
    AVATAR VARCHAR(500),
    DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_SYS_NOTICE_TYPE ON SYS_NOTICE(TYPE);
CREATE INDEX IF NOT EXISTS IDX_SYS_NOTICE_DATETIME ON SYS_NOTICE(DATETIME DESC);
