import org.apache.tools.ant.filters.ReplaceTokens

apply plugin: "org.springframework.boot"

project.tasks.publish.enabled = false

jar {
    enabled = true
}

bootJar {
    mainClass = 'tech.yunyue.WebBooter'
}

description = """web"""

compileJava.dependsOn(processResources)

processResources {
    println "==> Load configuration for $profile"
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    from(sourceSets.main.resources.srcDirs) {
        filter(ReplaceTokens, tokens: [profile: profile])
    }

}

dependencies {

    api     project(":yunyue-core:yunyue-core-web"),
            project(":yunyue-core:yunyue-core-data-mybatis"),
            project(":yunyue-web:yunyue-web-auth"),
            "${lib.mysql}"

    implementation "${lib.bootAdmin}",
                   "${lib.devTools}",
                   "${lib.springdocui}",
                   "${lib.knife4j_ui}"


}
