import org.apache.tools.ant.filters.ReplaceTokens

apply plugin: "org.springframework.boot"

project.tasks.publish.enabled = false

jar {
    enabled = true
}

bootJar {
    mainClass = 'org.pkaq.WebBooter'
}

description = """web"""

compileJava.dependsOn(processResources)

processResources {
    println "==> Load configuration for $profile"
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    from(sourceSets.main.resources.srcDirs) {
        filter(ReplaceTokens, tokens: [profile: profile])
    }
}

dependencies {

    implementation     project(":eva-core:eva-core-common"),
                       project(":eva-core:eva-core-data-mybatis"),
                       project(":eva-web:eva-web-sys:eva-web-sys-service"),
                       libs.mysql

    implementation(libs.web) {
        exclude module: 'spring-boot-starter-tomcat'
    }

    implementation libs.undertow

    implementation libs.springdocui,
                   libs.prometheus,
                   libs.actuator,
                   libs.knife4j.ui

    if (project.hasProperty('dev')) {
        runtimeOnly libs.dev.tools
    }
}