if (project.file('../../publish.gradle').exists()) {
    apply from: '../../publish.gradle'
}
jar {
    archiveBaseName = 'eva-core-log'
}
project.description = 'eva log support'

dependencies {
    implementation  project(":eva-core:eva-core-common")

    implementation libs.mybatis.plus.starter,
                   libs.jdbc
}
