apply plugin: "org.springframework.boot"

project.tasks.publish.enabled = false

jar {
    enabled = true
}
bootJar {
    mainClass = 'org.pkaq.core.LicenseBooter'
}

description = """license"""

// 依赖配置
dependencies {
    // 使用undertow替代tomcat
    implementation(libs.web){
        exclude module: 'spring-boot-starter-tomcat'
    }
    implementation project(":eva-core:eva-core-common"),
                   libs.truelicense

}
